name: hey_legend
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.21.1
  firebase_auth: ^3.7.0
  firebase_storage: ^10.3.7
  cloud_firestore: ^3.4.6
  google_sign_in: ^5.4.1
  get: ^4.6.5
  image_picker: ^0.8.5+3
  simple_circular_progress_bar: ^1.0.2
  clay_containers: ^0.3.2
  flutter_custom_clippers: ^2.0.0
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.15
  flutter_switch_clipper: ^0.0.5
  animator: ^3.2.0
  flutter_animator: ^3.2.2
  widget_circular_animator: ^1.0.0
  #
  dynamic_widget: ^4.0.5
  dropdown_button2:
  flutter_launcher_icons: ^0.10.0
  local_auth: ^2.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
#  dynamic_widget:
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/appIcon/appIcon.png"

builders:
  json_widget: any

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/onBoarding/
    - assets/appIcon/
